name: Jupyter Notebooks

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: Test Jupyter notebooks on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      DEVITO_ARCH: "${{ matrix.compiler }}"
      DEVITO_OPENMP: 1
      DEVITO_BACKEND: "core"
      PYTHON_VERSION: "3.7"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false
      matrix:
        name: [
          ubuntu-16.04-gcc-py37,
          macOS-10.14-gcc-py37
          ]

        include:
          - name: ubuntu-16.04-gcc-py37
            os: ubuntu-16.04
            compiler: gcc-7

          - name: macOS-10.14-gcc-py37
            os: macOS-10.14
            compiler: gcc

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install compilers
      run: |
        if [ "${{ matrix.compiler }}" = "gcc-7" ]; then
           sudo apt-get install -y mpich libmpich-dev
        else
           brew install gcc
           gcc --version
           brew install mpich
        fi

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[extras]

    - name: CFD notebooks
      run: |
        py.test --nbval examples/cfd

    - name: Seismic notebooks
      run: |
        py.test --nbval examples/seismic/tutorials/

    - name: MPI notebooks
      run: |
        py.test --nbval examples/mpi

    - name: User api notebooks
      run: |
        py.test --nbval examples/userapi
