name: push

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: push to other repo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1
      with:
        path: devito
  
    - name: Checkout pres
      uses: actions/checkout@v2
      with:
        repository: mloubout/presentations
        path: test

    - name: Commit results
      run: |
        git config --global user.email "mathias.louboutin@gmail.com"
        git config --global user.name "mloubout"
        git remote set-url --push origin https://mloubout:${{ secrets.PERSO }}@github.com/mloubout/presentations.git
        cp ../README.md .
        git add README.md
        git commit -m "readme"
        git push origin master
      working-directory: test
