name: push

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: push to other repo
    runs-on: ubuntu-latest

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Checkout prese
      uses: actions/checkout@v2
      with:
        repository: mloubout/presentations
        path: test

    - name: Commit results
      run: |
        cp ../devito/README.md .
        git add README.md
        git commit -m "readme"
        
    - name: Push results
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSO }}
        directory: website
        repository: mloubout/presentations
